apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- ns.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml # non-ha install
# - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/core-install.yaml # core install, without graphical components